package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"time"

	"connectrpc.com/connect"
	agrofierv1 "github.com/blingyplus/agrofie-backend/gen/agrofie/v1"
	"github.com/blingyplus/agrofie-backend/graph/gqlauth"
	"github.com/blingyplus/agrofie-backend/graph/model"
	"github.com/blingyplus/agrofie-backend/internal/discovery"
	"github.com/blingyplus/agrofie-backend/internal/lookup"
	"github.com/blingyplus/agrofie-backend/internal/talentprofile"
	"github.com/blingyplus/agrofie-backend/internal/verification"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	phone := ""
	if input.Phone != nil {
		phone = *input.Phone
	}
	res, err := r.AuthClient.Register(ctx, connect.NewRequest(&agrofierv1.RegisterRequest{
		Email:       input.Email,
		Phone:       phone,
		Password:    input.Password,
		DisplayName: input.DisplayName,
		RoleCode:    input.RoleCode,
	}))
	if err != nil {
		return nil, mapConnectErr(err)
	}
	return toAuthPayload(res.Msg.GetSession()), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	res, err := r.AuthClient.Login(ctx, connect.NewRequest(&agrofierv1.LoginRequest{
		Identifier: input.Identifier,
		Password:   input.Password,
	}))
	if err != nil {
		return nil, mapConnectErr(err)
	}
	return toAuthPayload(res.Msg.GetSession()), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	p, ok := gqlauth.FromContext(ctx)
	if !ok {
		return false, fmt.Errorf("unauthenticated")
	}
	_, err := r.AuthClient.Logout(ctx, connect.NewRequest(&agrofierv1.LogoutRequest{
		SessionToken: p.Token,
	}))
	if err != nil {
		return false, mapConnectErr(err)
	}
	return true, nil
}

// UpdateLookupName is the resolver for the updateLookupName field.
func (r *mutationResolver) UpdateLookupName(ctx context.Context, table model.LookupTable, code string, name string) (*model.Lookup, error) {
	item, err := r.Lookups.UpdateName(ctx, lookup.Table(table), code, name)
	if err != nil {
		return nil, err
	}
	return toLookup(item), nil
}

// SetLookupActive is the resolver for the setLookupActive field.
func (r *mutationResolver) SetLookupActive(ctx context.Context, table model.LookupTable, code string, isActive bool) (*model.Lookup, error) {
	item, err := r.Lookups.SetActive(ctx, lookup.Table(table), code, isActive)
	if err != nil {
		return nil, err
	}
	return toLookup(item), nil
}

// UpdateMyTalentProfile is the resolver for the updateMyTalentProfile field.
func (r *mutationResolver) UpdateMyTalentProfile(ctx context.Context, input model.UpdateTalentProfileInput) (*model.TalentProfile, error) {
	p, _ := gqlauth.FromContext(ctx)
	if err := r.TalentProfiles.UpdateBasics(ctx, p.UserID, toUpdateBasicsInput(input)); err != nil {
		return nil, mapTalentProfileErr(err)
	}
	return r.ownProfile(ctx, p.UserID)
}

// SetMyRates is the resolver for the setMyRates field.
func (r *mutationResolver) SetMyRates(ctx context.Context, rates []*model.RateInput) (*model.TalentProfile, error) {
	p, _ := gqlauth.FromContext(ctx)
	if err := r.TalentProfiles.SetRates(ctx, p.UserID, toRateInputs(rates)); err != nil {
		return nil, mapTalentProfileErr(err)
	}
	return r.ownProfile(ctx, p.UserID)
}

// ConnectMyPayoutAccount is the resolver for the connectMyPayoutAccount field.
func (r *mutationResolver) ConnectMyPayoutAccount(ctx context.Context, input model.ConnectPayoutInput) (*model.PayoutAccount, error) {
	p, _ := gqlauth.FromContext(ctx)
	out, err := r.TalentProfiles.ConnectPayout(ctx, p.UserID, toConnectPayoutInput(input))
	if err != nil {
		return nil, mapTalentProfileErr(err)
	}
	return toModelPayoutAccount(out), nil
}

// SubmitVerification is the resolver for the submitVerification field.
func (r *mutationResolver) SubmitVerification(ctx context.Context, input model.SubmitVerificationInput) (*model.Verification, error) {
	p, _ := gqlauth.FromContext(ctx)
	v, err := r.Verifications.Submit(ctx, p.UserID, verification.SubmitInput{
		TypeCode: input.TypeCode, EvidenceRef: input.EvidenceRef, Notes: input.Notes,
	})
	if err != nil {
		return nil, mapVerificationErr(err)
	}
	return toModelVerification(v), nil
}

// ApproveVerification is the resolver for the approveVerification field.
func (r *mutationResolver) ApproveVerification(ctx context.Context, id string, reviewNotes *string) (*model.Verification, error) {
	p, _ := gqlauth.FromContext(ctx)
	v, err := r.Verifications.Approve(ctx, p.UserID, id, reviewNotes)
	if err != nil {
		return nil, mapVerificationErr(err)
	}
	return toModelVerification(v), nil
}

// RejectVerification is the resolver for the rejectVerification field.
func (r *mutationResolver) RejectVerification(ctx context.Context, id string, reviewNotes *string) (*model.Verification, error) {
	p, _ := gqlauth.FromContext(ctx)
	v, err := r.Verifications.Reject(ctx, p.UserID, id, reviewNotes)
	if err != nil {
		return nil, mapVerificationErr(err)
	}
	return toModelVerification(v), nil
}

// AddMyAvailabilityBlock is the resolver for the addMyAvailabilityBlock field.
func (r *mutationResolver) AddMyAvailabilityBlock(ctx context.Context, input model.AddAvailabilityBlockInput) (*model.AvailabilityBlock, error) {
	p, _ := gqlauth.FromContext(ctx)
	in, err := toAddBlockInput(input)
	if err != nil {
		return nil, mapAvailabilityErr(err)
	}
	block, err := r.Availability.AddBlock(ctx, p.UserID, in)
	if err != nil {
		return nil, mapAvailabilityErr(err)
	}
	return toModelAvailabilityBlock(block), nil
}

// RemoveMyAvailabilityBlock is the resolver for the removeMyAvailabilityBlock field.
func (r *mutationResolver) RemoveMyAvailabilityBlock(ctx context.Context, id string) (bool, error) {
	p, _ := gqlauth.FromContext(ctx)
	if err := r.Availability.RemoveBlock(ctx, p.UserID, id); err != nil {
		return false, mapAvailabilityErr(err)
	}
	return true, nil
}

// RequestBooking is the resolver for the requestBooking field.
func (r *mutationResolver) RequestBooking(ctx context.Context, input model.RequestBookingInput) (*model.OrganizerBooking, error) {
	p, _ := gqlauth.FromContext(ctx)
	in, err := toRequestInput(input)
	if err != nil {
		return nil, mapBookingErr(err)
	}
	b, err := r.Bookings.RequestBooking(ctx, p.UserID, in)
	if err != nil {
		return nil, mapBookingErr(err)
	}
	return r.organizerBookingByID(ctx, b.ID)
}

// AcceptBooking is the resolver for the acceptBooking field.
func (r *mutationResolver) AcceptBooking(ctx context.Context, id string) (*model.TalentBooking, error) {
	p, _ := gqlauth.FromContext(ctx)
	if _, err := r.Bookings.AcceptBooking(ctx, p.UserID, id); err != nil {
		return nil, mapBookingErr(err)
	}
	return r.talentBookingByID(ctx, p.UserID, id)
}

// DeclineBooking is the resolver for the declineBooking field.
func (r *mutationResolver) DeclineBooking(ctx context.Context, id string) (*model.TalentBooking, error) {
	p, _ := gqlauth.FromContext(ctx)
	if _, err := r.Bookings.DeclineBooking(ctx, p.UserID, id); err != nil {
		return nil, mapBookingErr(err)
	}
	return r.talentBookingByID(ctx, p.UserID, id)
}

// CancelBooking is the resolver for the cancelBooking field.
func (r *mutationResolver) CancelBooking(ctx context.Context, id string) (*model.OrganizerBooking, error) {
	p, _ := gqlauth.FromContext(ctx)
	if _, err := r.Bookings.CancelBooking(ctx, p.UserID, id); err != nil {
		return nil, mapBookingErr(err)
	}
	return r.organizerBookingByID(ctx, id)
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	authStatus, booking, payments := r.Prober.Probe(ctx)
	status := "ok"
	if authStatus != "ok" || booking != "ok" || payments != "ok" {
		status = "degraded"
	}
	return &model.Health{
		Status:   status,
		Service:  "gateway",
		Auth:     authStatus,
		Booking:  booking,
		Payments: payments,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	p, ok := gqlauth.FromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}
	var phone *string
	if p.Phone != "" {
		phone = &p.Phone
	}
	return &model.User{
		ID:          p.UserID,
		Email:       p.Email,
		Phone:       phone,
		DisplayName: p.DisplayName,
		RoleCodes:   append([]string(nil), p.RoleCodes...),
	}, nil
}

// Countries is the resolver for the countries field.
func (r *queryResolver) Countries(ctx context.Context, activeOnly *bool) ([]*model.Country, error) {
	rows, err := r.Lookups.Countries(ctx, boolOr(activeOnly, true))
	if err != nil {
		return nil, err
	}
	out := make([]*model.Country, 0, len(rows))
	for _, row := range rows {
		out = append(out, &model.Country{
			ID:       row.ID,
			Code:     row.Code,
			Name:     row.Name,
			IsActive: row.IsActive,
		})
	}
	return out, nil
}

// GeoPlaces is the resolver for the geoPlaces field.
func (r *queryResolver) GeoPlaces(ctx context.Context, countryCode *string, parentCode *string, activeOnly *bool) ([]*model.GeoPlace, error) {
	cc := "GH"
	if countryCode != nil && *countryCode != "" {
		cc = *countryCode
	}
	rows, err := r.Lookups.GeoPlaces(ctx, cc, parentCode, boolOr(activeOnly, true))
	if err != nil {
		return nil, err
	}
	out := make([]*model.GeoPlace, 0, len(rows))
	for _, row := range rows {
		out = append(out, &model.GeoPlace{
			ID:         row.ID,
			Code:       row.Code,
			Name:       row.Name,
			PlaceLevel: row.PlaceLevel,
			ParentCode: row.ParentCode,
			IsActive:   row.IsActive,
		})
	}
	return out, nil
}

// Genres is the resolver for the genres field.
func (r *queryResolver) Genres(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.Genres)
}

// TalentTypes is the resolver for the talentTypes field.
func (r *queryResolver) TalentTypes(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.TalentTypes)
}

// EventTypes is the resolver for the eventTypes field.
func (r *queryResolver) EventTypes(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.EventTypes)
}

// Languages is the resolver for the languages field.
func (r *queryResolver) Languages(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.Languages)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.Roles)
}

// BookingStatuses is the resolver for the bookingStatuses field.
func (r *queryResolver) BookingStatuses(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.BookingStatuses)
}

// RateUnits is the resolver for the rateUnits field.
func (r *queryResolver) RateUnits(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.RateUnits)
}

// VerificationTypes is the resolver for the verificationTypes field.
func (r *queryResolver) VerificationTypes(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.VerificationTypes)
}

// MyVerifications is the resolver for the myVerifications field.
func (r *queryResolver) MyVerifications(ctx context.Context) ([]*model.Verification, error) {
	p, _ := gqlauth.FromContext(ctx)
	rows, err := r.Verifications.ListMine(ctx, p.UserID)
	if err != nil {
		return nil, mapVerificationErr(err)
	}
	out := make([]*model.Verification, 0, len(rows))
	for _, v := range rows {
		v := v
		out = append(out, toModelVerification(&v))
	}
	return out, nil
}

// PendingVerifications is the resolver for the pendingVerifications field.
func (r *queryResolver) PendingVerifications(ctx context.Context) ([]*model.PendingVerification, error) {
	rows, err := r.Verifications.ListPending(ctx)
	if err != nil {
		return nil, mapVerificationErr(err)
	}
	out := make([]*model.PendingVerification, 0, len(rows))
	for _, item := range rows {
		out = append(out, &model.PendingVerification{
			ID: item.ID, TalentUserID: item.TalentUserID, TalentDisplayName: item.TalentDisplayName,
			TypeCode: item.TypeCode, TypeName: item.TypeName, EvidenceRef: item.EvidenceRef, Notes: item.Notes,
		})
	}
	return out, nil
}

// SearchTalent is the resolver for the searchTalent field.
func (r *queryResolver) SearchTalent(ctx context.Context, filter *model.TalentFilter, first *int, after *string) (*model.TalentPage, error) {
	page, err := r.Discovery.Search(ctx, toDiscoveryFilter(filter), intOr(first, 0), stringOr(after, ""))
	if err != nil {
		return nil, mapDiscoveryErr(err)
	}
	return toTalentPage(page), nil
}

// Talent is the resolver for the talent field.
func (r *queryResolver) Talent(ctx context.Context, id string) (*model.TalentProfile, error) {
	p, err := r.Discovery.Get(ctx, id)
	if errors.Is(err, discovery.ErrNotFound) {
		return nil, nil // nullable: hidden, suspended and unknown talent look identical
	}
	if err != nil {
		return nil, mapDiscoveryErr(err)
	}
	return toTalentProfile(p), nil
}

// MyTalentProfile is the resolver for the myTalentProfile field.
func (r *queryResolver) MyTalentProfile(ctx context.Context) (*model.TalentProfile, error) {
	p, _ := gqlauth.FromContext(ctx)
	return r.ownProfile(ctx, p.UserID)
}

// SettlementBanks is the resolver for the settlementBanks field.
func (r *queryResolver) SettlementBanks(ctx context.Context, typeArg model.SettlementType) ([]*model.SettlementBank, error) {
	banks, err := r.TalentProfiles.ListSettlementBanks(ctx, toDomainSettlementType(typeArg))
	if err != nil {
		return nil, mapTalentProfileErr(err)
	}
	out := make([]*model.SettlementBank, 0, len(banks))
	for _, b := range banks {
		out = append(out, &model.SettlementBank{Name: b.Name, Code: b.Code})
	}
	return out, nil
}

// MyPayoutAccount is the resolver for the myPayoutAccount field.
func (r *queryResolver) MyPayoutAccount(ctx context.Context) (*model.PayoutAccount, error) {
	p, _ := gqlauth.FromContext(ctx)
	out, err := r.TalentProfiles.GetMyPayoutAccount(ctx, p.UserID)
	if errors.Is(err, talentprofile.ErrNoPayoutAccount) {
		return nil, nil
	}
	if err != nil {
		return nil, mapTalentProfileErr(err)
	}
	return toModelPayoutAccount(out), nil
}

// MyAvailability is the resolver for the myAvailability field.
func (r *queryResolver) MyAvailability(ctx context.Context, from string, to string) ([]*model.AvailabilityBlock, error) {
	p, _ := gqlauth.FromContext(ctx)
	fromT, toT, err := parseRange(from, to)
	if err != nil {
		return nil, mapAvailabilityErr(err)
	}
	blocks, err := r.Availability.ListMine(ctx, p.UserID, fromT, toT)
	if err != nil {
		return nil, mapAvailabilityErr(err)
	}
	out := make([]*model.AvailabilityBlock, 0, len(blocks))
	for _, b := range blocks {
		b := b
		out = append(out, toModelAvailabilityBlock(&b))
	}
	return out, nil
}

// TalentAvailability is the resolver for the talentAvailability field.
func (r *queryResolver) TalentAvailability(ctx context.Context, talentID string, from string, to string) ([]*model.AvailabilityWindow, error) {
	fromT, toT, err := parseRange(from, to)
	if err != nil {
		return nil, mapAvailabilityErr(err)
	}
	windows, err := r.Availability.ListForTalent(ctx, talentID, fromT, toT)
	if err != nil {
		return nil, mapAvailabilityErr(err)
	}
	out := make([]*model.AvailabilityWindow, 0, len(windows))
	for _, w := range windows {
		out = append(out, &model.AvailabilityWindow{
			ID: w.ID, StartsAt: w.StartsAt.Format(time.RFC3339), EndsAt: w.EndsAt.Format(time.RFC3339), IsAvailable: w.IsAvailable,
		})
	}
	return out, nil
}

// MyBookingsAsOrganizer is the resolver for the myBookingsAsOrganizer field.
func (r *queryResolver) MyBookingsAsOrganizer(ctx context.Context) ([]*model.OrganizerBooking, error) {
	p, _ := gqlauth.FromContext(ctx)
	rows, err := r.Bookings.ListMyBookingsAsOrganizer(ctx, p.UserID)
	if err != nil {
		return nil, mapBookingErr(err)
	}
	out := make([]*model.OrganizerBooking, 0, len(rows))
	for _, row := range rows {
		row := row
		out = append(out, toModelOrganizerBooking(&row))
	}
	return out, nil
}

// MyBookingsAsTalent is the resolver for the myBookingsAsTalent field.
func (r *queryResolver) MyBookingsAsTalent(ctx context.Context) ([]*model.TalentBooking, error) {
	p, _ := gqlauth.FromContext(ctx)
	rows, err := r.Bookings.ListMyBookingsAsTalent(ctx, p.UserID)
	if err != nil {
		return nil, mapBookingErr(err)
	}
	out := make([]*model.TalentBooking, 0, len(rows))
	for _, row := range rows {
		row := row
		out = append(out, toModelTalentBooking(&row))
	}
	return out, nil
}

// Booking is the resolver for the booking field.
func (r *queryResolver) Booking(ctx context.Context, id string) (*model.BookingDetail, error) {
	p, _ := gqlauth.FromContext(ctx)
	detail, err := r.Bookings.GetDetail(ctx, p.UserID, id)
	if err != nil {
		return nil, mapBookingErr(err)
	}
	return toModelBookingDetail(detail), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
