package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"

	"connectrpc.com/connect"
	agrofierv1 "github.com/blingyplus/agrofie-backend/gen/agrofie/v1"
	"github.com/blingyplus/agrofie-backend/graph/gqlauth"
	"github.com/blingyplus/agrofie-backend/graph/model"
	"github.com/blingyplus/agrofie-backend/internal/lookup"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	phone := ""
	if input.Phone != nil {
		phone = *input.Phone
	}
	res, err := r.AuthClient.Register(ctx, connect.NewRequest(&agrofierv1.RegisterRequest{
		Email:       input.Email,
		Phone:       phone,
		Password:    input.Password,
		DisplayName: input.DisplayName,
		RoleCode:    input.RoleCode,
	}))
	if err != nil {
		return nil, mapConnectErr(err)
	}
	return toAuthPayload(res.Msg.GetSession()), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	res, err := r.AuthClient.Login(ctx, connect.NewRequest(&agrofierv1.LoginRequest{
		Identifier: input.Identifier,
		Password:   input.Password,
	}))
	if err != nil {
		return nil, mapConnectErr(err)
	}
	return toAuthPayload(res.Msg.GetSession()), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	p, ok := gqlauth.FromContext(ctx)
	if !ok {
		return false, fmt.Errorf("unauthenticated")
	}
	_, err := r.AuthClient.Logout(ctx, connect.NewRequest(&agrofierv1.LogoutRequest{
		SessionToken: p.Token,
	}))
	if err != nil {
		return false, mapConnectErr(err)
	}
	return true, nil
}

// UpdateLookupName is the resolver for the updateLookupName field.
func (r *mutationResolver) UpdateLookupName(ctx context.Context, table model.LookupTable, code string, name string) (*model.Lookup, error) {
	item, err := r.Lookups.UpdateName(ctx, lookup.Table(table), code, name)
	if err != nil {
		return nil, err
	}
	return toLookup(item), nil
}

// SetLookupActive is the resolver for the setLookupActive field.
func (r *mutationResolver) SetLookupActive(ctx context.Context, table model.LookupTable, code string, isActive bool) (*model.Lookup, error) {
	item, err := r.Lookups.SetActive(ctx, lookup.Table(table), code, isActive)
	if err != nil {
		return nil, err
	}
	return toLookup(item), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	authStatus, booking, payments := r.Prober.Probe(ctx)
	status := "ok"
	if authStatus != "ok" || booking != "ok" || payments != "ok" {
		status = "degraded"
	}
	return &model.Health{
		Status:   status,
		Service:  "gateway",
		Auth:     authStatus,
		Booking:  booking,
		Payments: payments,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	p, ok := gqlauth.FromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}
	var phone *string
	if p.Phone != "" {
		phone = &p.Phone
	}
	return &model.User{
		ID:          p.UserID,
		Email:       p.Email,
		Phone:       phone,
		DisplayName: p.DisplayName,
		RoleCodes:   append([]string(nil), p.RoleCodes...),
	}, nil
}

// Countries is the resolver for the countries field.
func (r *queryResolver) Countries(ctx context.Context, activeOnly *bool) ([]*model.Country, error) {
	rows, err := r.Lookups.Countries(ctx, boolOr(activeOnly, true))
	if err != nil {
		return nil, err
	}
	out := make([]*model.Country, 0, len(rows))
	for _, row := range rows {
		out = append(out, &model.Country{
			ID:       row.ID,
			Code:     row.Code,
			Name:     row.Name,
			IsActive: row.IsActive,
		})
	}
	return out, nil
}

// GeoPlaces is the resolver for the geoPlaces field.
func (r *queryResolver) GeoPlaces(ctx context.Context, countryCode *string, parentCode *string, activeOnly *bool) ([]*model.GeoPlace, error) {
	cc := "GH"
	if countryCode != nil && *countryCode != "" {
		cc = *countryCode
	}
	rows, err := r.Lookups.GeoPlaces(ctx, cc, parentCode, boolOr(activeOnly, true))
	if err != nil {
		return nil, err
	}
	out := make([]*model.GeoPlace, 0, len(rows))
	for _, row := range rows {
		out = append(out, &model.GeoPlace{
			ID:         row.ID,
			Code:       row.Code,
			Name:       row.Name,
			PlaceLevel: row.PlaceLevel,
			ParentCode: row.ParentCode,
			IsActive:   row.IsActive,
		})
	}
	return out, nil
}

// Genres is the resolver for the genres field.
func (r *queryResolver) Genres(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.Genres)
}

// TalentTypes is the resolver for the talentTypes field.
func (r *queryResolver) TalentTypes(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.TalentTypes)
}

// EventTypes is the resolver for the eventTypes field.
func (r *queryResolver) EventTypes(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.EventTypes)
}

// Languages is the resolver for the languages field.
func (r *queryResolver) Languages(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.Languages)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.Roles)
}

// BookingStatuses is the resolver for the bookingStatuses field.
func (r *queryResolver) BookingStatuses(ctx context.Context, activeOnly *bool) ([]*model.Lookup, error) {
	return listLookups(ctx, boolOr(activeOnly, true), r.Lookups.BookingStatuses)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

func boolOr(v *bool, fallback bool) bool {
	if v == nil {
		return fallback
	}
	return *v
}

func toLookup(item *lookup.Item) *model.Lookup {
	return &model.Lookup{
		ID:        item.ID,
		Code:      item.Code,
		Name:      item.Name,
		SortOrder: int(item.SortOrder),
		IsActive:  item.IsActive,
	}
}

func listLookups(ctx context.Context, activeOnly bool, fn func(context.Context, bool) ([]lookup.Item, error)) ([]*model.Lookup, error) {
	rows, err := fn(ctx, activeOnly)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Lookup, 0, len(rows))
	for i := range rows {
		out = append(out, toLookup(&rows[i]))
	}
	return out, nil
}

func toAuthPayload(session *agrofierv1.AuthSession) *model.AuthPayload {
	if session == nil {
		return nil
	}
	return &model.AuthPayload{
		SessionToken: session.GetSessionToken(),
		User:         toModelUser(session.GetUser()),
	}
}

func toModelUser(u *agrofierv1.User) *model.User {
	if u == nil {
		return nil
	}
	var phone *string
	if u.GetPhone() != "" {
		p := u.GetPhone()
		phone = &p
	}
	return &model.User{
		ID:          u.GetId(),
		Email:       u.GetEmail(),
		Phone:       phone,
		DisplayName: u.GetDisplayName(),
		RoleCodes:   append([]string(nil), u.GetRoleCodes()...),
	}
}

func mapConnectErr(err error) error {
	var connectErr *connect.Error
	if errors.As(err, &connectErr) {
		return fmt.Errorf("%s", connectErr.Message())
	}
	return err
}
