// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuthPayload struct {
	SessionToken string `json:"sessionToken"`
	User         *User  `json:"user"`
}

type Country struct {
	ID       string `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"isActive"`
}

type GeoPlace struct {
	ID         string  `json:"id"`
	Code       string  `json:"code"`
	Name       string  `json:"name"`
	PlaceLevel string  `json:"placeLevel"`
	ParentCode *string `json:"parentCode,omitempty"`
	IsActive   bool    `json:"isActive"`
}

type Health struct {
	Status   string `json:"status"`
	Service  string `json:"service"`
	Auth     string `json:"auth"`
	Booking  string `json:"booking"`
	Payments string `json:"payments"`
}

type LoginInput struct {
	Identifier string `json:"identifier"`
	Password   string `json:"password"`
}

type Lookup struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int    `json:"sortOrder"`
	IsActive  bool   `json:"isActive"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email       string  `json:"email"`
	Phone       *string `json:"phone,omitempty"`
	Password    string  `json:"password"`
	DisplayName string  `json:"displayName"`
	RoleCode    string  `json:"roleCode"`
}

type User struct {
	ID          string   `json:"id"`
	Email       string   `json:"email"`
	Phone       *string  `json:"phone,omitempty"`
	DisplayName string   `json:"displayName"`
	RoleCodes   []string `json:"roleCodes"`
}

type LookupTable string

const (
	LookupTableGenres              LookupTable = "GENRES"
	LookupTableTalentTypes         LookupTable = "TALENT_TYPES"
	LookupTableEventTypes          LookupTable = "EVENT_TYPES"
	LookupTableLanguages           LookupTable = "LANGUAGES"
	LookupTableRoles               LookupTable = "ROLES"
	LookupTableBookingStatuses     LookupTable = "BOOKING_STATUSES"
	LookupTableDisputeReasons      LookupTable = "DISPUTE_REASONS"
	LookupTableCancellationReasons LookupTable = "CANCELLATION_REASONS"
)

var AllLookupTable = []LookupTable{
	LookupTableGenres,
	LookupTableTalentTypes,
	LookupTableEventTypes,
	LookupTableLanguages,
	LookupTableRoles,
	LookupTableBookingStatuses,
	LookupTableDisputeReasons,
	LookupTableCancellationReasons,
}

func (e LookupTable) IsValid() bool {
	switch e {
	case LookupTableGenres, LookupTableTalentTypes, LookupTableEventTypes, LookupTableLanguages, LookupTableRoles, LookupTableBookingStatuses, LookupTableDisputeReasons, LookupTableCancellationReasons:
		return true
	}
	return false
}

func (e LookupTable) String() string {
	return string(e)
}

func (e *LookupTable) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LookupTable(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LookupTable", str)
	}
	return nil
}

func (e LookupTable) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LookupTable) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LookupTable) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
