// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, display_name, legal_name, avatar_media_id, created_at, updated_at
FROM profiles
WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.LegalName,
		&i.AvatarMediaID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleIDByCode = `-- name: GetRoleIDByCode :one
SELECT id FROM roles WHERE code = $1
`

func (q *Queries) GetRoleIDByCode(ctx context.Context, code string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRoleIDByCode, code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, password_hash, user_status_id, kratos_identity_id, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID               pgtype.UUID        `json:"id"`
	Email            *string            `json:"email"`
	Phone            *string            `json:"phone"`
	PasswordHash     *string            `json:"password_hash"`
	UserStatusID     pgtype.UUID        `json:"user_status_id"`
	KratosIdentityID pgtype.UUID        `json:"kratos_identity_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserStatusID,
		&i.KratosIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, password_hash, user_status_id, kratos_identity_id, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	Email            *string            `json:"email"`
	Phone            *string            `json:"phone"`
	PasswordHash     *string            `json:"password_hash"`
	UserStatusID     pgtype.UUID        `json:"user_status_id"`
	KratosIdentityID pgtype.UUID        `json:"kratos_identity_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserStatusID,
		&i.KratosIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByKratosIdentityID = `-- name: GetUserByKratosIdentityID :one
SELECT id, email, phone, password_hash, user_status_id, kratos_identity_id, created_at, updated_at
FROM users
WHERE kratos_identity_id = $1
`

type GetUserByKratosIdentityIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	Email            *string            `json:"email"`
	Phone            *string            `json:"phone"`
	PasswordHash     *string            `json:"password_hash"`
	UserStatusID     pgtype.UUID        `json:"user_status_id"`
	KratosIdentityID pgtype.UUID        `json:"kratos_identity_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByKratosIdentityID(ctx context.Context, kratosIdentityID pgtype.UUID) (GetUserByKratosIdentityIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByKratosIdentityID, kratosIdentityID)
	var i GetUserByKratosIdentityIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserStatusID,
		&i.KratosIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, phone, password_hash, user_status_id, kratos_identity_id, created_at, updated_at
FROM users
WHERE phone = $1
`

type GetUserByPhoneRow struct {
	ID               pgtype.UUID        `json:"id"`
	Email            *string            `json:"email"`
	Phone            *string            `json:"phone"`
	PasswordHash     *string            `json:"password_hash"`
	UserStatusID     pgtype.UUID        `json:"user_status_id"`
	KratosIdentityID pgtype.UUID        `json:"kratos_identity_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserStatusID,
		&i.KratosIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStatusIDByCode = `-- name: GetUserStatusIDByCode :one
SELECT id FROM user_statuses WHERE code = $1
`

func (q *Queries) GetUserStatusIDByCode(ctx context.Context, code string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserStatusIDByCode, code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertOrganizerProfile = `-- name: InsertOrganizerProfile :one
INSERT INTO organizer_profiles (user_id)
VALUES ($1)
RETURNING id, user_id, organization, bio, created_at, updated_at
`

func (q *Queries) InsertOrganizerProfile(ctx context.Context, userID pgtype.UUID) (OrganizerProfile, error) {
	row := q.db.QueryRow(ctx, insertOrganizerProfile, userID)
	var i OrganizerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Organization,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProfile = `-- name: InsertProfile :one
INSERT INTO profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING id, user_id, display_name, legal_name, avatar_media_id, created_at, updated_at
`

type InsertProfileParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, insertProfile, arg.UserID, arg.DisplayName)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.LegalName,
		&i.AvatarMediaID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTalentProfile = `-- name: InsertTalentProfile :one
INSERT INTO talent_profiles (user_id)
VALUES ($1)
RETURNING id, user_id, headline, bio, home_geo_place_id, is_searchable, created_at, updated_at
`

func (q *Queries) InsertTalentProfile(ctx context.Context, userID pgtype.UUID) (TalentProfile, error) {
	row := q.db.QueryRow(ctx, insertTalentProfile, userID)
	var i TalentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Headline,
		&i.Bio,
		&i.HomeGeoPlaceID,
		&i.IsSearchable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, phone, user_status_id, kratos_identity_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, phone, password_hash, user_status_id, kratos_identity_id, created_at, updated_at
`

type InsertUserParams struct {
	Email            *string     `json:"email"`
	Phone            *string     `json:"phone"`
	UserStatusID     pgtype.UUID `json:"user_status_id"`
	KratosIdentityID pgtype.UUID `json:"kratos_identity_id"`
}

type InsertUserRow struct {
	ID               pgtype.UUID        `json:"id"`
	Email            *string            `json:"email"`
	Phone            *string            `json:"phone"`
	PasswordHash     *string            `json:"password_hash"`
	UserStatusID     pgtype.UUID        `json:"user_status_id"`
	KratosIdentityID pgtype.UUID        `json:"kratos_identity_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.Phone,
		arg.UserStatusID,
		arg.KratosIdentityID,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.UserStatusID,
		&i.KratosIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.UserID, arg.RoleID)
	return err
}

const listRoleCodesForUser = `-- name: ListRoleCodesForUser :many
SELECT r.code
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.sort_order, r.code
`

func (q *Queries) ListRoleCodesForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleCodesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
