// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAvailabilityBlock = `-- name: DeleteAvailabilityBlock :execrows
DELETE FROM availability_blocks WHERE id = $1 AND talent_profile_id = $2
`

type DeleteAvailabilityBlockParams struct {
	ID              pgtype.UUID `json:"id"`
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
}

func (q *Queries) DeleteAvailabilityBlock(ctx context.Context, arg DeleteAvailabilityBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailabilityBlock, arg.ID, arg.TalentProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAvailabilityBlockOwner = `-- name: GetAvailabilityBlockOwner :one
SELECT talent_profile_id FROM availability_blocks WHERE id = $1
`

func (q *Queries) GetAvailabilityBlockOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAvailabilityBlockOwner, id)
	var talent_profile_id pgtype.UUID
	err := row.Scan(&talent_profile_id)
	return talent_profile_id, err
}

const insertAvailabilityBlock = `-- name: InsertAvailabilityBlock :one
INSERT INTO availability_blocks (talent_profile_id, starts_at, ends_at, is_available, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, starts_at, ends_at, is_available, note
`

type InsertAvailabilityBlockParams struct {
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	IsAvailable     bool               `json:"is_available"`
	Note            *string            `json:"note"`
}

type InsertAvailabilityBlockRow struct {
	ID          pgtype.UUID        `json:"id"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	IsAvailable bool               `json:"is_available"`
	Note        *string            `json:"note"`
}

func (q *Queries) InsertAvailabilityBlock(ctx context.Context, arg InsertAvailabilityBlockParams) (InsertAvailabilityBlockRow, error) {
	row := q.db.QueryRow(ctx, insertAvailabilityBlock,
		arg.TalentProfileID,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsAvailable,
		arg.Note,
	)
	var i InsertAvailabilityBlockRow
	err := row.Scan(
		&i.ID,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsAvailable,
		&i.Note,
	)
	return i, err
}

const listMyAvailabilityBlocks = `-- name: ListMyAvailabilityBlocks :many
SELECT id, starts_at, ends_at, is_available, note
FROM availability_blocks
WHERE talent_profile_id = $1
  AND ends_at >= $2::timestamptz
  AND starts_at <= $3::timestamptz
ORDER BY starts_at
`

type ListMyAvailabilityBlocksParams struct {
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	FromTs          pgtype.Timestamptz `json:"from_ts"`
	ToTs            pgtype.Timestamptz `json:"to_ts"`
}

type ListMyAvailabilityBlocksRow struct {
	ID          pgtype.UUID        `json:"id"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	IsAvailable bool               `json:"is_available"`
	Note        *string            `json:"note"`
}

func (q *Queries) ListMyAvailabilityBlocks(ctx context.Context, arg ListMyAvailabilityBlocksParams) ([]ListMyAvailabilityBlocksRow, error) {
	rows, err := q.db.Query(ctx, listMyAvailabilityBlocks, arg.TalentProfileID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyAvailabilityBlocksRow{}
	for rows.Next() {
		var i ListMyAvailabilityBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsAvailable,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentAvailabilityWindows = `-- name: ListTalentAvailabilityWindows :many
SELECT id, starts_at, ends_at, is_available
FROM availability_blocks
WHERE talent_profile_id = $1
  AND ends_at >= $2::timestamptz
  AND starts_at <= $3::timestamptz
ORDER BY starts_at
`

type ListTalentAvailabilityWindowsParams struct {
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	FromTs          pgtype.Timestamptz `json:"from_ts"`
	ToTs            pgtype.Timestamptz `json:"to_ts"`
}

type ListTalentAvailabilityWindowsRow struct {
	ID          pgtype.UUID        `json:"id"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	IsAvailable bool               `json:"is_available"`
}

// Public-safe: no `note` (a talent's own reason for a blackout, e.g. "unwell",
// is not something organizers should see).
func (q *Queries) ListTalentAvailabilityWindows(ctx context.Context, arg ListTalentAvailabilityWindowsParams) ([]ListTalentAvailabilityWindowsRow, error) {
	rows, err := q.db.Query(ctx, listTalentAvailabilityWindows, arg.TalentProfileID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentAvailabilityWindowsRow{}
	for rows.Next() {
		var i ListTalentAvailabilityWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
