// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTalentBookable = `-- name: CheckTalentBookable :one
SELECT tp.is_searchable,
       EXISTS(SELECT 1 FROM payout_accounts pa WHERE pa.talent_profile_id = tp.id AND pa.is_active) AS has_payout
FROM talent_profiles tp
WHERE tp.id = $1
`

type CheckTalentBookableRow struct {
	IsSearchable bool `json:"is_searchable"`
	HasPayout    bool `json:"has_payout"`
}

func (q *Queries) CheckTalentBookable(ctx context.Context, id pgtype.UUID) (CheckTalentBookableRow, error) {
	row := q.db.QueryRow(ctx, checkTalentBookable, id)
	var i CheckTalentBookableRow
	err := row.Scan(&i.IsSearchable, &i.HasPayout)
	return i, err
}

const countConflictingAgreedBookings = `-- name: CountConflictingAgreedBookings :one
SELECT count(*) FROM bookings
WHERE talent_profile_id = $1
  AND booking_status_id = (SELECT id FROM booking_statuses WHERE code = 'agreed')
  AND starts_at < $2::timestamptz
  AND ends_at > $3::timestamptz
  AND ($4::uuid IS NULL OR id != $4::uuid)
`

type CountConflictingAgreedBookingsParams struct {
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	NewEndsAt       pgtype.Timestamptz `json:"new_ends_at"`
	NewStartsAt     pgtype.Timestamptz `json:"new_starts_at"`
	ExcludeID       pgtype.UUID        `json:"exclude_id"`
}

// Interval overlap test: an existing booking conflicts with the requested
// [new_starts_at, new_ends_at) window if it starts before the new window
// ends AND ends after the new window starts.
func (q *Queries) CountConflictingAgreedBookings(ctx context.Context, arg CountConflictingAgreedBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConflictingAgreedBookings,
		arg.TalentProfileID,
		arg.NewEndsAt,
		arg.NewStartsAt,
		arg.ExcludeID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBookingDetail = `-- name: GetBookingDetail :one
SELECT b.id, b.organizer_user_id, b.talent_profile_id, tp.user_id AS talent_user_id,
       b.starts_at, b.ends_at, b.venue_text,
       b.quoted_amount::text AS quoted_amount, b.currency_code,
       bs.code AS status_code, bs.name AS status_name,
       organizer_pr.display_name AS organizer_display_name,
       talent_pr.display_name AS talent_display_name,
       et.name AS event_type_name,
       c.terms_text
FROM bookings b
JOIN booking_statuses bs ON bs.id = b.booking_status_id
JOIN profiles organizer_pr ON organizer_pr.user_id = b.organizer_user_id
JOIN talent_profiles tp ON tp.id = b.talent_profile_id
JOIN profiles talent_pr ON talent_pr.user_id = tp.user_id
LEFT JOIN event_types et ON et.id = b.event_type_id
LEFT JOIN contracts c ON c.booking_id = b.id
WHERE b.id = $1
`

type GetBookingDetailRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizerUserID      pgtype.UUID        `json:"organizer_user_id"`
	TalentProfileID      pgtype.UUID        `json:"talent_profile_id"`
	TalentUserID         pgtype.UUID        `json:"talent_user_id"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	VenueText            *string            `json:"venue_text"`
	QuotedAmount         string             `json:"quoted_amount"`
	CurrencyCode         *string            `json:"currency_code"`
	StatusCode           string             `json:"status_code"`
	StatusName           string             `json:"status_name"`
	OrganizerDisplayName string             `json:"organizer_display_name"`
	TalentDisplayName    string             `json:"talent_display_name"`
	EventTypeName        *string            `json:"event_type_name"`
	TermsText            *string            `json:"terms_text"`
}

func (q *Queries) GetBookingDetail(ctx context.Context, id pgtype.UUID) (GetBookingDetailRow, error) {
	row := q.db.QueryRow(ctx, getBookingDetail, id)
	var i GetBookingDetailRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerUserID,
		&i.TalentProfileID,
		&i.TalentUserID,
		&i.StartsAt,
		&i.EndsAt,
		&i.VenueText,
		&i.QuotedAmount,
		&i.CurrencyCode,
		&i.StatusCode,
		&i.StatusName,
		&i.OrganizerDisplayName,
		&i.TalentDisplayName,
		&i.EventTypeName,
		&i.TermsText,
	)
	return i, err
}

const getBookingForTransition = `-- name: GetBookingForTransition :one
SELECT b.id, b.organizer_user_id, b.talent_profile_id, bs.code AS status_code, b.starts_at, b.ends_at
FROM bookings b
JOIN booking_statuses bs ON bs.id = b.booking_status_id
WHERE b.id = $1
`

type GetBookingForTransitionRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizerUserID pgtype.UUID        `json:"organizer_user_id"`
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	StatusCode      string             `json:"status_code"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) GetBookingForTransition(ctx context.Context, id pgtype.UUID) (GetBookingForTransitionRow, error) {
	row := q.db.QueryRow(ctx, getBookingForTransition, id)
	var i GetBookingForTransitionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerUserID,
		&i.TalentProfileID,
		&i.StatusCode,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const getCurrentRateForBooking = `-- name: GetCurrentRateForBooking :one
SELECT r.amount::text AS amount, cur.code AS currency_code
FROM talent_rates r
JOIN currencies cur ON cur.id = r.currency_id
JOIN rate_units ru ON ru.id = r.rate_unit_id
WHERE r.talent_profile_id = $1
  AND ru.code = $2
  AND r.effective_to IS NULL
  AND ($3::text IS NULL
       OR r.event_type_id = (SELECT id FROM event_types WHERE code = $3::text))
`

type GetCurrentRateForBookingParams struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
	EventTypeCode   *string     `json:"event_type_code"`
}

type GetCurrentRateForBookingRow struct {
	Amount       string `json:"amount"`
	CurrencyCode string `json:"currency_code"`
}

func (q *Queries) GetCurrentRateForBooking(ctx context.Context, arg GetCurrentRateForBookingParams) (GetCurrentRateForBookingRow, error) {
	row := q.db.QueryRow(ctx, getCurrentRateForBooking, arg.TalentProfileID, arg.Code, arg.EventTypeCode)
	var i GetCurrentRateForBookingRow
	err := row.Scan(&i.Amount, &i.CurrencyCode)
	return i, err
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings (
    organizer_user_id, talent_profile_id, event_type_id, geo_place_id,
    booking_status_id, starts_at, ends_at, venue_text, quoted_amount, currency_code
)
SELECT $1, $2,
       (SELECT id FROM event_types WHERE code = $8::text),
       (SELECT g.id FROM geo_places g JOIN countries c ON c.id = g.country_id WHERE c.code = 'GH' AND g.code = $9::text),
       (SELECT id FROM booking_statuses WHERE code = 'inquiry'),
       $3, $4, $5, $6, $7
RETURNING id, created_at
`

type InsertBookingParams struct {
	OrganizerUserID pgtype.UUID        `json:"organizer_user_id"`
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	VenueText       *string            `json:"venue_text"`
	QuotedAmount    pgtype.Numeric     `json:"quoted_amount"`
	CurrencyCode    *string            `json:"currency_code"`
	EventTypeCode   *string            `json:"event_type_code"`
	PlaceCode       *string            `json:"place_code"`
}

type InsertBookingRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (InsertBookingRow, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.OrganizerUserID,
		arg.TalentProfileID,
		arg.StartsAt,
		arg.EndsAt,
		arg.VenueText,
		arg.QuotedAmount,
		arg.CurrencyCode,
		arg.EventTypeCode,
		arg.PlaceCode,
	)
	var i InsertBookingRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertBookingStatusEvent = `-- name: InsertBookingStatusEvent :exec
INSERT INTO booking_status_events (booking_id, booking_status_id, actor_user_id, note)
SELECT $1, (SELECT id FROM booking_statuses WHERE code = $4::text), $2, $3
`

type InsertBookingStatusEventParams struct {
	BookingID   pgtype.UUID `json:"booking_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Note        *string     `json:"note"`
	StatusCode  string      `json:"status_code"`
}

func (q *Queries) InsertBookingStatusEvent(ctx context.Context, arg InsertBookingStatusEventParams) error {
	_, err := q.db.Exec(ctx, insertBookingStatusEvent,
		arg.BookingID,
		arg.ActorUserID,
		arg.Note,
		arg.StatusCode,
	)
	return err
}

const insertContract = `-- name: InsertContract :exec
INSERT INTO contracts (booking_id, terms_text, agreed_at) VALUES ($1, $2, now())
`

type InsertContractParams struct {
	BookingID pgtype.UUID `json:"booking_id"`
	TermsText string      `json:"terms_text"`
}

func (q *Queries) InsertContract(ctx context.Context, arg InsertContractParams) error {
	_, err := q.db.Exec(ctx, insertContract, arg.BookingID, arg.TermsText)
	return err
}

const listMyBookingsAsOrganizer = `-- name: ListMyBookingsAsOrganizer :many
SELECT b.id, b.starts_at, b.ends_at, b.venue_text, b.quoted_amount::text AS quoted_amount, b.currency_code,
       bs.code AS status_code, bs.name AS status_name,
       pr.display_name AS talent_display_name, b.talent_profile_id,
       et.name AS event_type_name, b.created_at
FROM bookings b
JOIN booking_statuses bs ON bs.id = b.booking_status_id
JOIN talent_profiles tp ON tp.id = b.talent_profile_id
JOIN profiles pr ON pr.user_id = tp.user_id
LEFT JOIN event_types et ON et.id = b.event_type_id
WHERE b.organizer_user_id = $1
ORDER BY b.created_at DESC
`

type ListMyBookingsAsOrganizerRow struct {
	ID                pgtype.UUID        `json:"id"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
	VenueText         *string            `json:"venue_text"`
	QuotedAmount      string             `json:"quoted_amount"`
	CurrencyCode      *string            `json:"currency_code"`
	StatusCode        string             `json:"status_code"`
	StatusName        string             `json:"status_name"`
	TalentDisplayName string             `json:"talent_display_name"`
	TalentProfileID   pgtype.UUID        `json:"talent_profile_id"`
	EventTypeName     *string            `json:"event_type_name"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMyBookingsAsOrganizer(ctx context.Context, organizerUserID pgtype.UUID) ([]ListMyBookingsAsOrganizerRow, error) {
	rows, err := q.db.Query(ctx, listMyBookingsAsOrganizer, organizerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyBookingsAsOrganizerRow{}
	for rows.Next() {
		var i ListMyBookingsAsOrganizerRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.VenueText,
			&i.QuotedAmount,
			&i.CurrencyCode,
			&i.StatusCode,
			&i.StatusName,
			&i.TalentDisplayName,
			&i.TalentProfileID,
			&i.EventTypeName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyBookingsAsTalent = `-- name: ListMyBookingsAsTalent :many
SELECT b.id, b.starts_at, b.ends_at, b.venue_text, b.quoted_amount::text AS quoted_amount, b.currency_code,
       bs.code AS status_code, bs.name AS status_name,
       pr.display_name AS organizer_display_name, b.organizer_user_id,
       et.name AS event_type_name, b.created_at
FROM bookings b
JOIN booking_statuses bs ON bs.id = b.booking_status_id
JOIN profiles pr ON pr.user_id = b.organizer_user_id
LEFT JOIN event_types et ON et.id = b.event_type_id
WHERE b.talent_profile_id = $1
ORDER BY b.created_at DESC
`

type ListMyBookingsAsTalentRow struct {
	ID                   pgtype.UUID        `json:"id"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	VenueText            *string            `json:"venue_text"`
	QuotedAmount         string             `json:"quoted_amount"`
	CurrencyCode         *string            `json:"currency_code"`
	StatusCode           string             `json:"status_code"`
	StatusName           string             `json:"status_name"`
	OrganizerDisplayName string             `json:"organizer_display_name"`
	OrganizerUserID      pgtype.UUID        `json:"organizer_user_id"`
	EventTypeName        *string            `json:"event_type_name"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMyBookingsAsTalent(ctx context.Context, talentProfileID pgtype.UUID) ([]ListMyBookingsAsTalentRow, error) {
	rows, err := q.db.Query(ctx, listMyBookingsAsTalent, talentProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyBookingsAsTalentRow{}
	for rows.Next() {
		var i ListMyBookingsAsTalentRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.VenueText,
			&i.QuotedAmount,
			&i.CurrencyCode,
			&i.StatusCode,
			&i.StatusName,
			&i.OrganizerDisplayName,
			&i.OrganizerUserID,
			&i.EventTypeName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :execrows
UPDATE bookings b
SET booking_status_id = (SELECT id FROM booking_statuses WHERE code = $1::text),
    cancellation_reason_id = (SELECT id FROM cancellation_reasons WHERE code = $2::text),
    updated_at = now()
FROM booking_statuses cur
WHERE b.id = $3::uuid AND b.booking_status_id = cur.id AND cur.code = $4::text
`

type UpdateBookingStatusParams struct {
	NewStatusCode          string      `json:"new_status_code"`
	CancellationReasonCode *string     `json:"cancellation_reason_code"`
	ID                     pgtype.UUID `json:"id"`
	ExpectedStatusCode     string      `json:"expected_status_code"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBookingStatus,
		arg.NewStatusCode,
		arg.CancellationReasonCode,
		arg.ID,
		arg.ExpectedStatusCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
