// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lookups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBookingStatuses = `-- name: ListBookingStatuses :many
SELECT id, code, name, sort_order, is_active
FROM booking_statuses
WHERE ($1::bool = false OR is_active = true)
ORDER BY sort_order, name
`

type ListBookingStatusesRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) ListBookingStatuses(ctx context.Context, activeOnly bool) ([]ListBookingStatusesRow, error) {
	rows, err := q.db.Query(ctx, listBookingStatuses, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingStatusesRow{}
	for rows.Next() {
		var i ListBookingStatusesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many
SELECT id, code, name, sort_order, is_active
FROM countries
WHERE ($1::bool = false OR is_active = true)
ORDER BY sort_order, name
`

type ListCountriesRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) ListCountries(ctx context.Context, activeOnly bool) ([]ListCountriesRow, error) {
	rows, err := q.db.Query(ctx, listCountries, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountriesRow{}
	for rows.Next() {
		var i ListCountriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTypes = `-- name: ListEventTypes :many
SELECT id, code, name, sort_order, is_active
FROM event_types
WHERE ($1::bool = false OR is_active = true)
ORDER BY sort_order, name
`

type ListEventTypesRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) ListEventTypes(ctx context.Context, activeOnly bool) ([]ListEventTypesRow, error) {
	rows, err := q.db.Query(ctx, listEventTypes, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventTypesRow{}
	for rows.Next() {
		var i ListEventTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenres = `-- name: ListGenres :many
SELECT id, code, name, sort_order, is_active
FROM genres
WHERE ($1::bool = false OR is_active = true)
ORDER BY sort_order, name
`

type ListGenresRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) ListGenres(ctx context.Context, activeOnly bool) ([]ListGenresRow, error) {
	rows, err := q.db.Query(ctx, listGenres, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenresRow{}
	for rows.Next() {
		var i ListGenresRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeoPlaces = `-- name: ListGeoPlaces :many
SELECT
  g.id,
  g.code,
  g.name,
  g.place_level,
  p.code AS parent_code,
  g.is_active,
  g.sort_order
FROM geo_places g
JOIN countries c ON c.id = g.country_id
LEFT JOIN geo_places p ON p.id = g.parent_id
WHERE c.code = $1
  AND (
    ($2::text IS NULL AND g.parent_id IS NULL)
    OR p.code = $2
  )
  AND ($3::bool = false OR g.is_active = true)
ORDER BY g.sort_order, g.name
`

type ListGeoPlacesParams struct {
	CountryCode string  `json:"country_code"`
	ParentCode  *string `json:"parent_code"`
	ActiveOnly  bool    `json:"active_only"`
}

type ListGeoPlacesRow struct {
	ID         pgtype.UUID `json:"id"`
	Code       string      `json:"code"`
	Name       string      `json:"name"`
	PlaceLevel string      `json:"place_level"`
	ParentCode *string     `json:"parent_code"`
	IsActive   bool        `json:"is_active"`
	SortOrder  int32       `json:"sort_order"`
}

func (q *Queries) ListGeoPlaces(ctx context.Context, arg ListGeoPlacesParams) ([]ListGeoPlacesRow, error) {
	rows, err := q.db.Query(ctx, listGeoPlaces, arg.CountryCode, arg.ParentCode, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeoPlacesRow{}
	for rows.Next() {
		var i ListGeoPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.PlaceLevel,
			&i.ParentCode,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguages = `-- name: ListLanguages :many
SELECT id, code, name, sort_order, is_active
FROM languages
WHERE ($1::bool = false OR is_active = true)
ORDER BY sort_order, name
`

type ListLanguagesRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) ListLanguages(ctx context.Context, activeOnly bool) ([]ListLanguagesRow, error) {
	rows, err := q.db.Query(ctx, listLanguages, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLanguagesRow{}
	for rows.Next() {
		var i ListLanguagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, code, name, sort_order, is_active
FROM roles
WHERE ($1::bool = false OR is_active = true)
ORDER BY sort_order, name
`

type ListRolesRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) ListRoles(ctx context.Context, activeOnly bool) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentTypes = `-- name: ListTalentTypes :many
SELECT id, code, name, sort_order, is_active
FROM talent_types
WHERE ($1::bool = false OR is_active = true)
ORDER BY sort_order, name
`

type ListTalentTypesRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) ListTalentTypes(ctx context.Context, activeOnly bool) ([]ListTalentTypesRow, error) {
	rows, err := q.db.Query(ctx, listTalentTypes, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentTypesRow{}
	for rows.Next() {
		var i ListTalentTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookingStatusActive = `-- name: SetBookingStatusActive :one
UPDATE booking_statuses
SET is_active = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type SetBookingStatusActiveParams struct {
	IsActive bool   `json:"is_active"`
	Code     string `json:"code"`
}

type SetBookingStatusActiveRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetBookingStatusActive(ctx context.Context, arg SetBookingStatusActiveParams) (SetBookingStatusActiveRow, error) {
	row := q.db.QueryRow(ctx, setBookingStatusActive, arg.IsActive, arg.Code)
	var i SetBookingStatusActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const setCancellationReasonActive = `-- name: SetCancellationReasonActive :one
UPDATE cancellation_reasons
SET is_active = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type SetCancellationReasonActiveParams struct {
	IsActive bool   `json:"is_active"`
	Code     string `json:"code"`
}

type SetCancellationReasonActiveRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetCancellationReasonActive(ctx context.Context, arg SetCancellationReasonActiveParams) (SetCancellationReasonActiveRow, error) {
	row := q.db.QueryRow(ctx, setCancellationReasonActive, arg.IsActive, arg.Code)
	var i SetCancellationReasonActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const setDisputeReasonActive = `-- name: SetDisputeReasonActive :one
UPDATE dispute_reasons
SET is_active = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type SetDisputeReasonActiveParams struct {
	IsActive bool   `json:"is_active"`
	Code     string `json:"code"`
}

type SetDisputeReasonActiveRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetDisputeReasonActive(ctx context.Context, arg SetDisputeReasonActiveParams) (SetDisputeReasonActiveRow, error) {
	row := q.db.QueryRow(ctx, setDisputeReasonActive, arg.IsActive, arg.Code)
	var i SetDisputeReasonActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const setEventTypeActive = `-- name: SetEventTypeActive :one
UPDATE event_types
SET is_active = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type SetEventTypeActiveParams struct {
	IsActive bool   `json:"is_active"`
	Code     string `json:"code"`
}

type SetEventTypeActiveRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetEventTypeActive(ctx context.Context, arg SetEventTypeActiveParams) (SetEventTypeActiveRow, error) {
	row := q.db.QueryRow(ctx, setEventTypeActive, arg.IsActive, arg.Code)
	var i SetEventTypeActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const setGenreActive = `-- name: SetGenreActive :one
UPDATE genres
SET is_active = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type SetGenreActiveParams struct {
	IsActive bool   `json:"is_active"`
	Code     string `json:"code"`
}

type SetGenreActiveRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetGenreActive(ctx context.Context, arg SetGenreActiveParams) (SetGenreActiveRow, error) {
	row := q.db.QueryRow(ctx, setGenreActive, arg.IsActive, arg.Code)
	var i SetGenreActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const setLanguageActive = `-- name: SetLanguageActive :one
UPDATE languages
SET is_active = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type SetLanguageActiveParams struct {
	IsActive bool   `json:"is_active"`
	Code     string `json:"code"`
}

type SetLanguageActiveRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetLanguageActive(ctx context.Context, arg SetLanguageActiveParams) (SetLanguageActiveRow, error) {
	row := q.db.QueryRow(ctx, setLanguageActive, arg.IsActive, arg.Code)
	var i SetLanguageActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const setRoleActive = `-- name: SetRoleActive :one
UPDATE roles
SET is_active = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type SetRoleActiveParams struct {
	IsActive bool   `json:"is_active"`
	Code     string `json:"code"`
}

type SetRoleActiveRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetRoleActive(ctx context.Context, arg SetRoleActiveParams) (SetRoleActiveRow, error) {
	row := q.db.QueryRow(ctx, setRoleActive, arg.IsActive, arg.Code)
	var i SetRoleActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const setTalentTypeActive = `-- name: SetTalentTypeActive :one
UPDATE talent_types
SET is_active = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type SetTalentTypeActiveParams struct {
	IsActive bool   `json:"is_active"`
	Code     string `json:"code"`
}

type SetTalentTypeActiveRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SetTalentTypeActive(ctx context.Context, arg SetTalentTypeActiveParams) (SetTalentTypeActiveRow, error) {
	row := q.db.QueryRow(ctx, setTalentTypeActive, arg.IsActive, arg.Code)
	var i SetTalentTypeActiveRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const updateBookingStatusName = `-- name: UpdateBookingStatusName :one
UPDATE booking_statuses
SET name = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type UpdateBookingStatusNameParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type UpdateBookingStatusNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateBookingStatusName(ctx context.Context, arg UpdateBookingStatusNameParams) (UpdateBookingStatusNameRow, error) {
	row := q.db.QueryRow(ctx, updateBookingStatusName, arg.Name, arg.Code)
	var i UpdateBookingStatusNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const updateCancellationReasonName = `-- name: UpdateCancellationReasonName :one
UPDATE cancellation_reasons
SET name = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type UpdateCancellationReasonNameParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type UpdateCancellationReasonNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateCancellationReasonName(ctx context.Context, arg UpdateCancellationReasonNameParams) (UpdateCancellationReasonNameRow, error) {
	row := q.db.QueryRow(ctx, updateCancellationReasonName, arg.Name, arg.Code)
	var i UpdateCancellationReasonNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const updateDisputeReasonName = `-- name: UpdateDisputeReasonName :one
UPDATE dispute_reasons
SET name = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type UpdateDisputeReasonNameParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type UpdateDisputeReasonNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateDisputeReasonName(ctx context.Context, arg UpdateDisputeReasonNameParams) (UpdateDisputeReasonNameRow, error) {
	row := q.db.QueryRow(ctx, updateDisputeReasonName, arg.Name, arg.Code)
	var i UpdateDisputeReasonNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const updateEventTypeName = `-- name: UpdateEventTypeName :one
UPDATE event_types
SET name = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type UpdateEventTypeNameParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type UpdateEventTypeNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateEventTypeName(ctx context.Context, arg UpdateEventTypeNameParams) (UpdateEventTypeNameRow, error) {
	row := q.db.QueryRow(ctx, updateEventTypeName, arg.Name, arg.Code)
	var i UpdateEventTypeNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const updateGenreName = `-- name: UpdateGenreName :one
UPDATE genres
SET name = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type UpdateGenreNameParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type UpdateGenreNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateGenreName(ctx context.Context, arg UpdateGenreNameParams) (UpdateGenreNameRow, error) {
	row := q.db.QueryRow(ctx, updateGenreName, arg.Name, arg.Code)
	var i UpdateGenreNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const updateLanguageName = `-- name: UpdateLanguageName :one
UPDATE languages
SET name = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type UpdateLanguageNameParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type UpdateLanguageNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateLanguageName(ctx context.Context, arg UpdateLanguageNameParams) (UpdateLanguageNameRow, error) {
	row := q.db.QueryRow(ctx, updateLanguageName, arg.Name, arg.Code)
	var i UpdateLanguageNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const updateRoleName = `-- name: UpdateRoleName :one
UPDATE roles
SET name = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type UpdateRoleNameParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type UpdateRoleNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) (UpdateRoleNameRow, error) {
	row := q.db.QueryRow(ctx, updateRoleName, arg.Name, arg.Code)
	var i UpdateRoleNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const updateTalentTypeName = `-- name: UpdateTalentTypeName :one
UPDATE talent_types
SET name = $1, updated_at = now()
WHERE code = $2
RETURNING id, code, name, sort_order, is_active
`

type UpdateTalentTypeNameParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type UpdateTalentTypeNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateTalentTypeName(ctx context.Context, arg UpdateTalentTypeNameParams) (UpdateTalentTypeNameRow, error) {
	row := q.db.QueryRow(ctx, updateTalentTypeName, arg.Name, arg.Code)
	var i UpdateTalentTypeNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}
