// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilityBlock struct {
	ID              pgtype.UUID        `json:"id"`
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	IsAvailable     bool               `json:"is_available"`
	Note            *string            `json:"note"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizerUserID      pgtype.UUID        `json:"organizer_user_id"`
	TalentProfileID      pgtype.UUID        `json:"talent_profile_id"`
	EventTypeID          pgtype.UUID        `json:"event_type_id"`
	GeoPlaceID           pgtype.UUID        `json:"geo_place_id"`
	BookingStatusID      pgtype.UUID        `json:"booking_status_id"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	VenueText            *string            `json:"venue_text"`
	QuotedAmount         pgtype.Numeric     `json:"quoted_amount"`
	CurrencyCode         *string            `json:"currency_code"`
	CancellationReasonID pgtype.UUID        `json:"cancellation_reason_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BookingStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BookingStatusEvent struct {
	ID              pgtype.UUID        `json:"id"`
	BookingID       pgtype.UUID        `json:"booking_id"`
	BookingStatusID pgtype.UUID        `json:"booking_status_id"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	Note            *string            `json:"note"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type CancellationReason struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Contract struct {
	ID        pgtype.UUID        `json:"id"`
	BookingID pgtype.UUID        `json:"booking_id"`
	TermsText string             `json:"terms_text"`
	AgreedAt  pgtype.Timestamptz `json:"agreed_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Country struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Currency struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Dispute struct {
	ID              pgtype.UUID        `json:"id"`
	BookingID       pgtype.UUID        `json:"booking_id"`
	OpenedByUserID  pgtype.UUID        `json:"opened_by_user_id"`
	DisputeReasonID pgtype.UUID        `json:"dispute_reason_id"`
	DisputeStatusID pgtype.UUID        `json:"dispute_status_id"`
	Details         *string            `json:"details"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DisputeReason struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DisputeStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EscrowLedger struct {
	ID                pgtype.UUID        `json:"id"`
	BookingID         pgtype.UUID        `json:"booking_id"`
	LedgerEntryTypeID pgtype.UUID        `json:"ledger_entry_type_id"`
	LedgerStatusID    pgtype.UUID        `json:"ledger_status_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	CurrencyCode      string             `json:"currency_code"`
	ProviderRef       *string            `json:"provider_ref"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type EventType struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Genre struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GeoPlace struct {
	ID         pgtype.UUID        `json:"id"`
	CountryID  pgtype.UUID        `json:"country_id"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	PlaceLevel string             `json:"place_level"`
	SortOrder  int32              `json:"sort_order"`
	IsActive   bool               `json:"is_active"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Language struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LedgerEntryType struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LedgerStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MediaAsset struct {
	ID              pgtype.UUID        `json:"id"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	MediaTypeID     pgtype.UUID        `json:"media_type_id"`
	Url             string             `json:"url"`
	Title           *string            `json:"title"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type MediaType struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizerProfile struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Organization *string            `json:"organization"`
	Bio          *string            `json:"bio"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DisplayName   string             `json:"display_name"`
	LegalName     *string            `json:"legal_name"`
	AvatarMediaID pgtype.UUID        `json:"avatar_media_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RateUnit struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID           pgtype.UUID        `json:"id"`
	BookingID    pgtype.UUID        `json:"booking_id"`
	AuthorUserID pgtype.UUID        `json:"author_user_id"`
	Rating       int16              `json:"rating"`
	Body         *string            `json:"body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TalentGenre struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	GenreID         pgtype.UUID `json:"genre_id"`
}

type TalentLanguage struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	LanguageID      pgtype.UUID `json:"language_id"`
}

type TalentProfile struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Headline       *string            `json:"headline"`
	Bio            *string            `json:"bio"`
	HomeGeoPlaceID pgtype.UUID        `json:"home_geo_place_id"`
	IsSearchable   bool               `json:"is_searchable"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TalentRate struct {
	ID              pgtype.UUID        `json:"id"`
	TalentProfileID pgtype.UUID        `json:"talent_profile_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	CurrencyID      pgtype.UUID        `json:"currency_id"`
	RateUnitID      pgtype.UUID        `json:"rate_unit_id"`
	EventTypeID     pgtype.UUID        `json:"event_type_id"`
	EffectiveFrom   pgtype.Timestamptz `json:"effective_from"`
	EffectiveTo     pgtype.Timestamptz `json:"effective_to"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TalentServiceArea struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	GeoPlaceID      pgtype.UUID `json:"geo_place_id"`
}

type TalentType struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TalentTypesMap struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	TalentTypeID    pgtype.UUID `json:"talent_type_id"`
}

type User struct {
	ID               pgtype.UUID        `json:"id"`
	Email            *string            `json:"email"`
	Phone            *string            `json:"phone"`
	PasswordHash     *string            `json:"password_hash"`
	UserStatusID     pgtype.UUID        `json:"user_status_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	KratosIdentityID pgtype.UUID        `json:"kratos_identity_id"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Verification struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	VerificationTypeID   pgtype.UUID        `json:"verification_type_id"`
	VerificationStatusID pgtype.UUID        `json:"verification_status_id"`
	EvidenceRef          *string            `json:"evidence_ref"`
	Notes                *string            `json:"notes"`
	ReviewedBy           pgtype.UUID        `json:"reviewed_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type VerificationStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type VerificationType struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
