// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBookingForCheckout = `-- name: GetBookingForCheckout :one
SELECT b.id, b.organizer_user_id, u.email AS organizer_email,
       b.talent_profile_id, bs.code AS status_code,
       b.quoted_amount::text AS quoted_amount, b.currency_code,
       pa.provider_subaccount_code, pa.is_active AS payout_active
FROM bookings b
JOIN booking_statuses bs ON bs.id = b.booking_status_id
JOIN users u ON u.id = b.organizer_user_id
LEFT JOIN payout_accounts pa ON pa.talent_profile_id = b.talent_profile_id AND pa.is_active
WHERE b.id = $1
`

type GetBookingForCheckoutRow struct {
	ID                     pgtype.UUID `json:"id"`
	OrganizerUserID        pgtype.UUID `json:"organizer_user_id"`
	OrganizerEmail         *string     `json:"organizer_email"`
	TalentProfileID        pgtype.UUID `json:"talent_profile_id"`
	StatusCode             string      `json:"status_code"`
	QuotedAmount           string      `json:"quoted_amount"`
	CurrencyCode           *string     `json:"currency_code"`
	ProviderSubaccountCode *string     `json:"provider_subaccount_code"`
	PayoutActive           *bool       `json:"payout_active"`
}

// Everything InitiateCheckout needs, in one row: who is paying (organizer),
// who is being paid (talent's subaccount), and the server-trusted amount.
func (q *Queries) GetBookingForCheckout(ctx context.Context, id pgtype.UUID) (GetBookingForCheckoutRow, error) {
	row := q.db.QueryRow(ctx, getBookingForCheckout, id)
	var i GetBookingForCheckoutRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerUserID,
		&i.OrganizerEmail,
		&i.TalentProfileID,
		&i.StatusCode,
		&i.QuotedAmount,
		&i.CurrencyCode,
		&i.ProviderSubaccountCode,
		&i.PayoutActive,
	)
	return i, err
}

const getLatestPaymentForBooking = `-- name: GetLatestPaymentForBooking :one
SELECT p.id, p.provider_reference, p.amount_pesewas, p.commission_pesewas,
       p.currency_code, p.checkout_url, ps.code AS status_code, ps.name AS status_name,
       p.created_at, p.updated_at
FROM payments p
JOIN payment_statuses ps ON ps.id = p.payment_status_id
WHERE p.booking_id = $1
ORDER BY p.created_at DESC
LIMIT 1
`

type GetLatestPaymentForBookingRow struct {
	ID                pgtype.UUID        `json:"id"`
	ProviderReference string             `json:"provider_reference"`
	AmountPesewas     int64              `json:"amount_pesewas"`
	CommissionPesewas int64              `json:"commission_pesewas"`
	CurrencyCode      string             `json:"currency_code"`
	CheckoutUrl       *string            `json:"checkout_url"`
	StatusCode        string             `json:"status_code"`
	StatusName        string             `json:"status_name"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLatestPaymentForBooking(ctx context.Context, bookingID pgtype.UUID) (GetLatestPaymentForBookingRow, error) {
	row := q.db.QueryRow(ctx, getLatestPaymentForBooking, bookingID)
	var i GetLatestPaymentForBookingRow
	err := row.Scan(
		&i.ID,
		&i.ProviderReference,
		&i.AmountPesewas,
		&i.CommissionPesewas,
		&i.CurrencyCode,
		&i.CheckoutUrl,
		&i.StatusCode,
		&i.StatusName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT p.id, p.booking_id, p.provider_reference, ps.code AS status_code
FROM payments p
JOIN payment_statuses ps ON ps.id = p.payment_status_id
WHERE p.provider_reference = $1
`

type GetPaymentByReferenceRow struct {
	ID                pgtype.UUID `json:"id"`
	BookingID         pgtype.UUID `json:"booking_id"`
	ProviderReference string      `json:"provider_reference"`
	StatusCode        string      `json:"status_code"`
}

func (q *Queries) GetPaymentByReference(ctx context.Context, providerReference string) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, providerReference)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ProviderReference,
		&i.StatusCode,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (
    booking_id, payment_status_id, provider_reference,
    amount_pesewas, commission_pesewas, currency_code, checkout_url
) VALUES (
    $1, (SELECT id FROM payment_statuses WHERE code = 'pending'),
    $2, $3, $4, $5, $6
)
RETURNING id, created_at
`

type InsertPaymentParams struct {
	BookingID         pgtype.UUID `json:"booking_id"`
	ProviderReference string      `json:"provider_reference"`
	AmountPesewas     int64       `json:"amount_pesewas"`
	CommissionPesewas int64       `json:"commission_pesewas"`
	CurrencyCode      string      `json:"currency_code"`
	CheckoutUrl       *string     `json:"checkout_url"`
}

type InsertPaymentRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (InsertPaymentRow, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.BookingID,
		arg.ProviderReference,
		arg.AmountPesewas,
		arg.CommissionPesewas,
		arg.CurrencyCode,
		arg.CheckoutUrl,
	)
	var i InsertPaymentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :execrows
INSERT INTO payment_events (provider_reference, event_type, payload)
VALUES ($1, $2, $3)
ON CONFLICT (provider_reference, event_type) DO NOTHING
`

type InsertPaymentEventParams struct {
	ProviderReference string `json:"provider_reference"`
	EventType         string `json:"event_type"`
	Payload           []byte `json:"payload"`
}

// ON CONFLICT DO NOTHING is the webhook idempotency guard: a retried
// delivery of the same (reference, event_type) affects zero rows, which the
// caller treats as "already handled".
func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPaymentEvent, arg.ProviderReference, arg.EventType, arg.Payload)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePaymentStatusByReference = `-- name: UpdatePaymentStatusByReference :execrows
UPDATE payments
SET payment_status_id = (SELECT id FROM payment_statuses WHERE code = $1::text),
    updated_at = now()
WHERE provider_reference = $2::text
`

type UpdatePaymentStatusByReferenceParams struct {
	StatusCode        string `json:"status_code"`
	ProviderReference string `json:"provider_reference"`
}

func (q *Queries) UpdatePaymentStatusByReference(ctx context.Context, arg UpdatePaymentStatusByReferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentStatusByReference, arg.StatusCode, arg.ProviderReference)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
