// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBookingForReview = `-- name: GetBookingForReview :one
SELECT b.id, b.organizer_user_id, tp.user_id AS talent_user_id, bs.code AS status_code
FROM bookings b
JOIN booking_statuses bs ON bs.id = b.booking_status_id
JOIN talent_profiles tp ON tp.id = b.talent_profile_id
WHERE b.id = $1
`

type GetBookingForReviewRow struct {
	ID              pgtype.UUID `json:"id"`
	OrganizerUserID pgtype.UUID `json:"organizer_user_id"`
	TalentUserID    pgtype.UUID `json:"talent_user_id"`
	StatusCode      string      `json:"status_code"`
}

func (q *Queries) GetBookingForReview(ctx context.Context, id pgtype.UUID) (GetBookingForReviewRow, error) {
	row := q.db.QueryRow(ctx, getBookingForReview, id)
	var i GetBookingForReviewRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerUserID,
		&i.TalentUserID,
		&i.StatusCode,
	)
	return i, err
}

const getTalentReviewSummary = `-- name: GetTalentReviewSummary :one
SELECT count(*) AS review_count, COALESCE(avg(r.rating), 0)::float8 AS average_rating
FROM reviews r
JOIN bookings b ON b.id = r.booking_id
WHERE b.talent_profile_id = $1 AND r.author_user_id = b.organizer_user_id
`

type GetTalentReviewSummaryRow struct {
	ReviewCount   int64   `json:"review_count"`
	AverageRating float64 `json:"average_rating"`
}

// Aggregate rating for a talent: every review the *organizer* left about
// one of the talent's bookings (the talent's own review of the organizer
// doesn't count toward the talent's rating).
func (q *Queries) GetTalentReviewSummary(ctx context.Context, talentProfileID pgtype.UUID) (GetTalentReviewSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTalentReviewSummary, talentProfileID)
	var i GetTalentReviewSummaryRow
	err := row.Scan(&i.ReviewCount, &i.AverageRating)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (booking_id, author_user_id, rating, body)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type InsertReviewParams struct {
	BookingID    pgtype.UUID `json:"booking_id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
	Rating       int16       `json:"rating"`
	Body         *string     `json:"body"`
}

type InsertReviewRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (InsertReviewRow, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.BookingID,
		arg.AuthorUserID,
		arg.Rating,
		arg.Body,
	)
	var i InsertReviewRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listReviewsForBooking = `-- name: ListReviewsForBooking :many
SELECT r.id, r.rating, r.body, r.created_at, r.author_user_id, pr.display_name AS author_display_name
FROM reviews r
JOIN profiles pr ON pr.user_id = r.author_user_id
WHERE r.booking_id = $1
ORDER BY r.created_at ASC
`

type ListReviewsForBookingRow struct {
	ID                pgtype.UUID        `json:"id"`
	Rating            int16              `json:"rating"`
	Body              *string            `json:"body"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	AuthorUserID      pgtype.UUID        `json:"author_user_id"`
	AuthorDisplayName string             `json:"author_display_name"`
}

func (q *Queries) ListReviewsForBooking(ctx context.Context, bookingID pgtype.UUID) ([]ListReviewsForBookingRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsForBookingRow{}
	for rows.Next() {
		var i ListReviewsForBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUserID,
			&i.AuthorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
