// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: talent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSearchableTalent = `-- name: GetSearchableTalent :one
SELECT tp.id, tp.headline, tp.bio, tp.created_at, pr.display_name, hp.name AS home_place_name
FROM talent_profiles tp
JOIN profiles pr ON pr.user_id = tp.user_id
JOIN users u ON u.id = tp.user_id
JOIN user_statuses us ON us.id = u.user_status_id AND us.code = 'active'
LEFT JOIN geo_places hp ON hp.id = tp.home_geo_place_id
WHERE tp.id = $1 AND tp.is_searchable
`

type GetSearchableTalentRow struct {
	ID            pgtype.UUID        `json:"id"`
	Headline      *string            `json:"headline"`
	Bio           *string            `json:"bio"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DisplayName   string             `json:"display_name"`
	HomePlaceName *string            `json:"home_place_name"`
}

func (q *Queries) GetSearchableTalent(ctx context.Context, id pgtype.UUID) (GetSearchableTalentRow, error) {
	row := q.db.QueryRow(ctx, getSearchableTalent, id)
	var i GetSearchableTalentRow
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Bio,
		&i.CreatedAt,
		&i.DisplayName,
		&i.HomePlaceName,
	)
	return i, err
}

const listCurrentRatesForTalent = `-- name: ListCurrentRatesForTalent :many
SELECT r.talent_profile_id,
       r.amount::text AS amount,
       cur.code AS currency_code,
       ru.code AS rate_unit_code,
       et.code AS event_type_code
FROM talent_rates r
JOIN currencies cur ON cur.id = r.currency_id
JOIN rate_units ru ON ru.id = r.rate_unit_id
LEFT JOIN event_types et ON et.id = r.event_type_id
WHERE r.talent_profile_id = ANY($1::uuid[])
  AND r.effective_to IS NULL
  AND r.effective_from <= now()
ORDER BY r.amount ASC
`

type ListCurrentRatesForTalentRow struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Amount          string      `json:"amount"`
	CurrencyCode    string      `json:"currency_code"`
	RateUnitCode    string      `json:"rate_unit_code"`
	EventTypeCode   *string     `json:"event_type_code"`
}

func (q *Queries) ListCurrentRatesForTalent(ctx context.Context, ids []pgtype.UUID) ([]ListCurrentRatesForTalentRow, error) {
	rows, err := q.db.Query(ctx, listCurrentRatesForTalent, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentRatesForTalentRow{}
	for rows.Next() {
		var i ListCurrentRatesForTalentRow
		if err := rows.Scan(
			&i.TalentProfileID,
			&i.Amount,
			&i.CurrencyCode,
			&i.RateUnitCode,
			&i.EventTypeCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenresForTalent = `-- name: ListGenresForTalent :many
SELECT tg.talent_profile_id, g.code, g.name
FROM talent_genres tg
JOIN genres g ON g.id = tg.genre_id
WHERE tg.talent_profile_id = ANY($1::uuid[])
ORDER BY g.sort_order, g.name
`

type ListGenresForTalentRow struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
}

func (q *Queries) ListGenresForTalent(ctx context.Context, ids []pgtype.UUID) ([]ListGenresForTalentRow, error) {
	rows, err := q.db.Query(ctx, listGenresForTalent, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenresForTalentRow{}
	for rows.Next() {
		var i ListGenresForTalentRow
		if err := rows.Scan(&i.TalentProfileID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguagesForTalent = `-- name: ListLanguagesForTalent :many
SELECT tl.talent_profile_id, l.code, l.name
FROM talent_languages tl
JOIN languages l ON l.id = tl.language_id
WHERE tl.talent_profile_id = ANY($1::uuid[])
ORDER BY l.sort_order, l.name
`

type ListLanguagesForTalentRow struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
}

func (q *Queries) ListLanguagesForTalent(ctx context.Context, ids []pgtype.UUID) ([]ListLanguagesForTalentRow, error) {
	rows, err := q.db.Query(ctx, listLanguagesForTalent, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLanguagesForTalentRow{}
	for rows.Next() {
		var i ListLanguagesForTalentRow
		if err := rows.Scan(&i.TalentProfileID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceAreasForTalent = `-- name: ListServiceAreasForTalent :many
SELECT sa.talent_profile_id, g.code, g.name
FROM talent_service_areas sa
JOIN geo_places g ON g.id = sa.geo_place_id
WHERE sa.talent_profile_id = ANY($1::uuid[])
ORDER BY g.sort_order, g.name
`

type ListServiceAreasForTalentRow struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
}

func (q *Queries) ListServiceAreasForTalent(ctx context.Context, ids []pgtype.UUID) ([]ListServiceAreasForTalentRow, error) {
	rows, err := q.db.Query(ctx, listServiceAreasForTalent, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceAreasForTalentRow{}
	for rows.Next() {
		var i ListServiceAreasForTalentRow
		if err := rows.Scan(&i.TalentProfileID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypesForTalent = `-- name: ListTypesForTalent :many
SELECT tm.talent_profile_id, t.code, t.name
FROM talent_types_map tm
JOIN talent_types t ON t.id = tm.talent_type_id
WHERE tm.talent_profile_id = ANY($1::uuid[])
ORDER BY t.sort_order, t.name
`

type ListTypesForTalentRow struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
}

func (q *Queries) ListTypesForTalent(ctx context.Context, ids []pgtype.UUID) ([]ListTypesForTalentRow, error) {
	rows, err := q.db.Query(ctx, listTypesForTalent, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTypesForTalentRow{}
	for rows.Next() {
		var i ListTypesForTalentRow
		if err := rows.Scan(&i.TalentProfileID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTalent = `-- name: SearchTalent :many

WITH RECURSIVE place_subtree AS (
    SELECT g.id
    FROM geo_places g
    JOIN countries c ON c.id = g.country_id
    WHERE $4::text <> ''
      AND c.code = $8::text
      AND g.code = $4::text
    UNION ALL
    SELECT g.id
    FROM geo_places g
    JOIN place_subtree s ON g.parent_id = s.id
)
SELECT tp.id, tp.headline, tp.created_at, pr.display_name, hp.name AS home_place_name
FROM talent_profiles tp
JOIN profiles pr ON pr.user_id = tp.user_id
JOIN users u ON u.id = tp.user_id
JOIN user_statuses us ON us.id = u.user_status_id AND us.code = 'active'
LEFT JOIN geo_places hp ON hp.id = tp.home_geo_place_id
WHERE tp.is_searchable
  AND (cardinality($1::text[]) = 0 OR EXISTS (
        SELECT 1 FROM talent_genres tg JOIN genres g ON g.id = tg.genre_id
        WHERE tg.talent_profile_id = tp.id AND g.code = ANY($1::text[])))
  AND (cardinality($2::text[]) = 0 OR EXISTS (
        SELECT 1 FROM talent_types_map tm JOIN talent_types t ON t.id = tm.talent_type_id
        WHERE tm.talent_profile_id = tp.id AND t.code = ANY($2::text[])))
  AND (cardinality($3::text[]) = 0 OR EXISTS (
        SELECT 1 FROM talent_languages tl JOIN languages l ON l.id = tl.language_id
        WHERE tl.talent_profile_id = tp.id AND l.code = ANY($3::text[])))
  AND ($4::text = '' OR EXISTS (
        SELECT 1 FROM place_subtree ps
        WHERE ps.id = tp.home_geo_place_id
           OR EXISTS (SELECT 1 FROM talent_service_areas sa
                      WHERE sa.talent_profile_id = tp.id AND sa.geo_place_id = ps.id)))
  AND ($5::uuid IS NULL
       OR (tp.created_at, tp.id) < ($6::timestamptz, $5::uuid))
ORDER BY tp.created_at DESC, tp.id DESC
LIMIT $7::int
`

type SearchTalentParams struct {
	GenreCodes      []string           `json:"genre_codes"`
	TypeCodes       []string           `json:"type_codes"`
	LanguageCodes   []string           `json:"language_codes"`
	PlaceCode       string             `json:"place_code"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	PageSize        int32              `json:"page_size"`
	CountryCode     string             `json:"country_code"`
}

type SearchTalentRow struct {
	ID            pgtype.UUID        `json:"id"`
	Headline      *string            `json:"headline"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DisplayName   string             `json:"display_name"`
	HomePlaceName *string            `json:"home_place_name"`
}

// Discovery reads. These never select users.email / users.phone: contact details
// stay hidden until a booking is agreed.
func (q *Queries) SearchTalent(ctx context.Context, arg SearchTalentParams) ([]SearchTalentRow, error) {
	rows, err := q.db.Query(ctx, searchTalent,
		arg.GenreCodes,
		arg.TypeCodes,
		arg.LanguageCodes,
		arg.PlaceCode,
		arg.CursorID,
		arg.CursorCreatedAt,
		arg.PageSize,
		arg.CountryCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTalentRow{}
	for rows.Next() {
		var i SearchTalentRow
		if err := rows.Scan(
			&i.ID,
			&i.Headline,
			&i.CreatedAt,
			&i.DisplayName,
			&i.HomePlaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
