// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: talent_profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTalentGenre = `-- name: AddTalentGenre :execrows
INSERT INTO talent_genres (talent_profile_id, genre_id) SELECT $1, id FROM genres WHERE code = $2
`

type AddTalentGenreParams struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
}

func (q *Queries) AddTalentGenre(ctx context.Context, arg AddTalentGenreParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTalentGenre, arg.TalentProfileID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addTalentLanguage = `-- name: AddTalentLanguage :execrows
INSERT INTO talent_languages (talent_profile_id, language_id) SELECT $1, id FROM languages WHERE code = $2
`

type AddTalentLanguageParams struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
}

func (q *Queries) AddTalentLanguage(ctx context.Context, arg AddTalentLanguageParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTalentLanguage, arg.TalentProfileID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addTalentServiceArea = `-- name: AddTalentServiceArea :execrows
INSERT INTO talent_service_areas (talent_profile_id, geo_place_id)
SELECT $1, g.id FROM geo_places g JOIN countries c ON c.id = g.country_id
WHERE c.code = 'GH' AND g.code = $2
`

type AddTalentServiceAreaParams struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
}

func (q *Queries) AddTalentServiceArea(ctx context.Context, arg AddTalentServiceAreaParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTalentServiceArea, arg.TalentProfileID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addTalentType = `-- name: AddTalentType :execrows
INSERT INTO talent_types_map (talent_profile_id, talent_type_id) SELECT $1, id FROM talent_types WHERE code = $2
`

type AddTalentTypeParams struct {
	TalentProfileID pgtype.UUID `json:"talent_profile_id"`
	Code            string      `json:"code"`
}

func (q *Queries) AddTalentType(ctx context.Context, arg AddTalentTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTalentType, arg.TalentProfileID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearTalentGenres = `-- name: ClearTalentGenres :exec
DELETE FROM talent_genres WHERE talent_profile_id = $1
`

func (q *Queries) ClearTalentGenres(ctx context.Context, talentProfileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTalentGenres, talentProfileID)
	return err
}

const clearTalentLanguages = `-- name: ClearTalentLanguages :exec
DELETE FROM talent_languages WHERE talent_profile_id = $1
`

func (q *Queries) ClearTalentLanguages(ctx context.Context, talentProfileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTalentLanguages, talentProfileID)
	return err
}

const clearTalentServiceAreas = `-- name: ClearTalentServiceAreas :exec
DELETE FROM talent_service_areas WHERE talent_profile_id = $1
`

func (q *Queries) ClearTalentServiceAreas(ctx context.Context, talentProfileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTalentServiceAreas, talentProfileID)
	return err
}

const clearTalentTypes = `-- name: ClearTalentTypes :exec
DELETE FROM talent_types_map WHERE talent_profile_id = $1
`

func (q *Queries) ClearTalentTypes(ctx context.Context, talentProfileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTalentTypes, talentProfileID)
	return err
}

const closeCurrentTalentRates = `-- name: CloseCurrentTalentRates :exec
UPDATE talent_rates SET effective_to = now() WHERE talent_profile_id = $1 AND effective_to IS NULL
`

func (q *Queries) CloseCurrentTalentRates(ctx context.Context, talentProfileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, closeCurrentTalentRates, talentProfileID)
	return err
}

const geoPlaceIDByCode = `-- name: GeoPlaceIDByCode :one
SELECT g.id FROM geo_places g JOIN countries c ON c.id = g.country_id
WHERE c.code = 'GH' AND g.code = $1
`

func (q *Queries) GeoPlaceIDByCode(ctx context.Context, code string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, geoPlaceIDByCode, code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getOwnTalentProfileBasics = `-- name: GetOwnTalentProfileBasics :one
SELECT tp.id, tp.headline, tp.bio, pr.display_name, hp.name AS home_place_name
FROM talent_profiles tp
JOIN profiles pr ON pr.user_id = tp.user_id
LEFT JOIN geo_places hp ON hp.id = tp.home_geo_place_id
WHERE tp.user_id = $1
`

type GetOwnTalentProfileBasicsRow struct {
	ID            pgtype.UUID `json:"id"`
	Headline      *string     `json:"headline"`
	Bio           *string     `json:"bio"`
	DisplayName   string      `json:"display_name"`
	HomePlaceName *string     `json:"home_place_name"`
}

// Unlike discovery's GetSearchableTalent, this has no is_searchable gate: a
// talent must be able to see and edit their own profile before verification.
func (q *Queries) GetOwnTalentProfileBasics(ctx context.Context, userID pgtype.UUID) (GetOwnTalentProfileBasicsRow, error) {
	row := q.db.QueryRow(ctx, getOwnTalentProfileBasics, userID)
	var i GetOwnTalentProfileBasicsRow
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Bio,
		&i.DisplayName,
		&i.HomePlaceName,
	)
	return i, err
}

const getPayoutAccountByTalentProfileID = `-- name: GetPayoutAccountByTalentProfileID :one
SELECT settlement_type, bank_name, account_number_last4, account_name, is_active, updated_at
FROM payout_accounts WHERE talent_profile_id = $1 AND is_active
`

type GetPayoutAccountByTalentProfileIDRow struct {
	SettlementType     string             `json:"settlement_type"`
	BankName           string             `json:"bank_name"`
	AccountNumberLast4 string             `json:"account_number_last4"`
	AccountName        string             `json:"account_name"`
	IsActive           bool               `json:"is_active"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPayoutAccountByTalentProfileID(ctx context.Context, talentProfileID pgtype.UUID) (GetPayoutAccountByTalentProfileIDRow, error) {
	row := q.db.QueryRow(ctx, getPayoutAccountByTalentProfileID, talentProfileID)
	var i GetPayoutAccountByTalentProfileIDRow
	err := row.Scan(
		&i.SettlementType,
		&i.BankName,
		&i.AccountNumberLast4,
		&i.AccountName,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const getTalentProfileIDByUserID = `-- name: GetTalentProfileIDByUserID :one

SELECT id FROM talent_profiles WHERE user_id = $1
`

// Talent-owned writes. Every mutation here operates on the caller's own
// talent_profile_id, resolved server-side from the authenticated principal.
func (q *Queries) GetTalentProfileIDByUserID(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTalentProfileIDByUserID, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTalentRate = `-- name: InsertTalentRate :execrows
INSERT INTO talent_rates (talent_profile_id, amount, currency_id, rate_unit_id, event_type_id, effective_from)
SELECT $1, $2::numeric, cur.id, ru.id,
       (SELECT id FROM event_types WHERE code = $3::text),
       now()
FROM currencies cur, rate_units ru
WHERE cur.code = $4::text AND ru.code = $5::text
`

type InsertTalentRateParams struct {
	TalentProfileID pgtype.UUID    `json:"talent_profile_id"`
	Column2         pgtype.Numeric `json:"column_2"`
	EventTypeCode   *string        `json:"event_type_code"`
	CurrencyCode    string         `json:"currency_code"`
	RateUnitCode    string         `json:"rate_unit_code"`
}

func (q *Queries) InsertTalentRate(ctx context.Context, arg InsertTalentRateParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTalentRate,
		arg.TalentProfileID,
		arg.Column2,
		arg.EventTypeCode,
		arg.CurrencyCode,
		arg.RateUnitCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTalentProfileBasics = `-- name: UpdateTalentProfileBasics :exec
UPDATE talent_profiles
SET headline = $2, bio = $3, home_geo_place_id = $4, updated_at = now()
WHERE talent_profiles.id = $1
`

type UpdateTalentProfileBasicsParams struct {
	ID             pgtype.UUID `json:"id"`
	Headline       *string     `json:"headline"`
	Bio            *string     `json:"bio"`
	HomeGeoPlaceID pgtype.UUID `json:"home_geo_place_id"`
}

// home_geo_place_id: pass a resolved UUID (looked up via GeoPlaceIDByCode) or
// NULL to clear it. Never pass an unvalidated code straight into this query.
func (q *Queries) UpdateTalentProfileBasics(ctx context.Context, arg UpdateTalentProfileBasicsParams) error {
	_, err := q.db.Exec(ctx, updateTalentProfileBasics,
		arg.ID,
		arg.Headline,
		arg.Bio,
		arg.HomeGeoPlaceID,
	)
	return err
}

const upsertPayoutAccount = `-- name: UpsertPayoutAccount :one
INSERT INTO payout_accounts (
    talent_profile_id, settlement_type, bank_code, bank_name,
    account_number_last4, account_name, provider_subaccount_code
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (talent_profile_id) DO UPDATE SET
    settlement_type = EXCLUDED.settlement_type,
    bank_code = EXCLUDED.bank_code,
    bank_name = EXCLUDED.bank_name,
    account_number_last4 = EXCLUDED.account_number_last4,
    account_name = EXCLUDED.account_name,
    provider_subaccount_code = EXCLUDED.provider_subaccount_code,
    is_active = TRUE,
    updated_at = now()
RETURNING id, updated_at
`

type UpsertPayoutAccountParams struct {
	TalentProfileID        pgtype.UUID `json:"talent_profile_id"`
	SettlementType         string      `json:"settlement_type"`
	BankCode               string      `json:"bank_code"`
	BankName               string      `json:"bank_name"`
	AccountNumberLast4     string      `json:"account_number_last4"`
	AccountName            string      `json:"account_name"`
	ProviderSubaccountCode string      `json:"provider_subaccount_code"`
}

type UpsertPayoutAccountRow struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPayoutAccount(ctx context.Context, arg UpsertPayoutAccountParams) (UpsertPayoutAccountRow, error) {
	row := q.db.QueryRow(ctx, upsertPayoutAccount,
		arg.TalentProfileID,
		arg.SettlementType,
		arg.BankCode,
		arg.BankName,
		arg.AccountNumberLast4,
		arg.AccountName,
		arg.ProviderSubaccountCode,
	)
	var i UpsertPayoutAccountRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}
