// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVerificationByID = `-- name: GetVerificationByID :one
SELECT v.id, vt.code AS type_code, vt.name AS type_name,
       vs.code AS status_code, vs.name AS status_name,
       v.evidence_ref, v.notes, v.review_notes, v.created_at
FROM verifications v
JOIN verification_types vt ON vt.id = v.verification_type_id
JOIN verification_statuses vs ON vs.id = v.verification_status_id
WHERE v.id = $1
`

type GetVerificationByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	TypeCode    string             `json:"type_code"`
	TypeName    string             `json:"type_name"`
	StatusCode  string             `json:"status_code"`
	StatusName  string             `json:"status_name"`
	EvidenceRef *string            `json:"evidence_ref"`
	Notes       *string            `json:"notes"`
	ReviewNotes *string            `json:"review_notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetVerificationByID(ctx context.Context, id pgtype.UUID) (GetVerificationByIDRow, error) {
	row := q.db.QueryRow(ctx, getVerificationByID, id)
	var i GetVerificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.TypeCode,
		&i.TypeName,
		&i.StatusCode,
		&i.StatusName,
		&i.EvidenceRef,
		&i.Notes,
		&i.ReviewNotes,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationForReview = `-- name: GetVerificationForReview :one
SELECT v.id, v.user_id, vt.code AS type_code, vs.code AS status_code
FROM verifications v
JOIN verification_types vt ON vt.id = v.verification_type_id
JOIN verification_statuses vs ON vs.id = v.verification_status_id
WHERE v.id = $1
`

type GetVerificationForReviewRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	TypeCode   string      `json:"type_code"`
	StatusCode string      `json:"status_code"`
}

func (q *Queries) GetVerificationForReview(ctx context.Context, id pgtype.UUID) (GetVerificationForReviewRow, error) {
	row := q.db.QueryRow(ctx, getVerificationForReview, id)
	var i GetVerificationForReviewRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TypeCode,
		&i.StatusCode,
	)
	return i, err
}

const insertVerification = `-- name: InsertVerification :one
INSERT INTO verifications (user_id, verification_type_id, verification_status_id, evidence_ref, notes)
SELECT $1, vt.id, vs.id, $3, $4
FROM verification_types vt, verification_statuses vs
WHERE vt.code = $2 AND vs.code = 'pending'
RETURNING id
`

type InsertVerificationParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Code        string      `json:"code"`
	EvidenceRef *string     `json:"evidence_ref"`
	Notes       *string     `json:"notes"`
}

func (q *Queries) InsertVerification(ctx context.Context, arg InsertVerificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertVerification,
		arg.UserID,
		arg.Code,
		arg.EvidenceRef,
		arg.Notes,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listMyVerifications = `-- name: ListMyVerifications :many
SELECT v.id, vt.code AS type_code, vt.name AS type_name,
       vs.code AS status_code, vs.name AS status_name,
       v.evidence_ref, v.notes, v.review_notes, v.created_at
FROM verifications v
JOIN verification_types vt ON vt.id = v.verification_type_id
JOIN verification_statuses vs ON vs.id = v.verification_status_id
WHERE v.user_id = $1
ORDER BY v.created_at DESC
`

type ListMyVerificationsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TypeCode    string             `json:"type_code"`
	TypeName    string             `json:"type_name"`
	StatusCode  string             `json:"status_code"`
	StatusName  string             `json:"status_name"`
	EvidenceRef *string            `json:"evidence_ref"`
	Notes       *string            `json:"notes"`
	ReviewNotes *string            `json:"review_notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMyVerifications(ctx context.Context, userID pgtype.UUID) ([]ListMyVerificationsRow, error) {
	rows, err := q.db.Query(ctx, listMyVerifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyVerificationsRow{}
	for rows.Next() {
		var i ListMyVerificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TypeCode,
			&i.TypeName,
			&i.StatusCode,
			&i.StatusName,
			&i.EvidenceRef,
			&i.Notes,
			&i.ReviewNotes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingVerifications = `-- name: ListPendingVerifications :many
SELECT v.id, v.user_id, pr.display_name AS talent_display_name,
       vt.code AS type_code, vt.name AS type_name,
       v.evidence_ref, v.notes, v.created_at
FROM verifications v
JOIN verification_types vt ON vt.id = v.verification_type_id
JOIN verification_statuses vs ON vs.id = v.verification_status_id
JOIN profiles pr ON pr.user_id = v.user_id
WHERE vs.code = 'pending'
ORDER BY v.created_at ASC
`

type ListPendingVerificationsRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	TalentDisplayName string             `json:"talent_display_name"`
	TypeCode          string             `json:"type_code"`
	TypeName          string             `json:"type_name"`
	EvidenceRef       *string            `json:"evidence_ref"`
	Notes             *string            `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingVerifications(ctx context.Context) ([]ListPendingVerificationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingVerifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingVerificationsRow{}
	for rows.Next() {
		var i ListPendingVerificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TalentDisplayName,
			&i.TypeCode,
			&i.TypeName,
			&i.EvidenceRef,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewVerification = `-- name: ReviewVerification :execrows
UPDATE verifications v
SET verification_status_id = (SELECT id FROM verification_statuses WHERE code = $4::text),
    reviewed_by = $2,
    review_notes = $3,
    updated_at = now()
FROM verification_statuses cur
WHERE v.id = $1 AND v.verification_status_id = cur.id AND cur.code = 'pending'
`

type ReviewVerificationParams struct {
	ID            pgtype.UUID `json:"id"`
	ReviewedBy    pgtype.UUID `json:"reviewed_by"`
	ReviewNotes   *string     `json:"review_notes"`
	NewStatusCode string      `json:"new_status_code"`
}

// Only ever moves a verification out of `pending`; re-reviewing an
// already-decided one affects zero rows (caller treats that as an error).
func (q *Queries) ReviewVerification(ctx context.Context, arg ReviewVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviewVerification,
		arg.ID,
		arg.ReviewedBy,
		arg.ReviewNotes,
		arg.NewStatusCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTalentSearchableByUserID = `-- name: SetTalentSearchableByUserID :execrows
UPDATE talent_profiles SET is_searchable = $2, updated_at = now() WHERE user_id = $1
`

type SetTalentSearchableByUserIDParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	IsSearchable bool        `json:"is_searchable"`
}

func (q *Queries) SetTalentSearchableByUserID(ctx context.Context, arg SetTalentSearchableByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTalentSearchableByUserID, arg.UserID, arg.IsSearchable)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
